name: Dialyzer Nightly

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: ci
    name: OTP ${{matrix.pair.otp}} / Elixir ${{matrix.pair.elixir}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              otp: 24.0.1
              elixir: 1.12.1
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - run: mix do deps.get, compile
      - run: mix ci
