name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    name: OTP ${{matrix.pair.otp}} / Elixir ${{matrix.pair.elixir}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              otp: 24.0.1
              elixir: 1.12.1
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: Install → Compile dependencies
        run: |
          mix do deps.get, compile
      - name: Run tests
        run: |
          rm _build/test/lib/tyx/ebin/Elixir.Tyx.Samples.Deft.beam
          mix test
